receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

  # Dummy receiver that's never used, because a pipeline is required to have one.
  # otlp/spanmetrics:
  #   protocols:
  #     grpc:
  #       # endpoint: "localhost:65535"
  #     http:
  #       cors:
  #         allowed_origins:
  #           - http://*
  #           - https://*

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  prometheus:
    # endpoint: "0.0.0.0:9464"
    endpoint: "0.0.0.0:8889"
    # endpoint: "prometheus:9464"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    # dimensions:
    #   - name: http.method
    #     default: GET
    #   - name: http.status_code
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA" 

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [spanmetrics, batch]
      # processors: [batch]
    # metrics:
    #   receivers: [otlp]
    #   exporters: [prometheus]
    #   processors: [batch]

    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
